defmodule Esi.Api.CorporationsCorporationIdContainersLogsGet do
  @moduledoc """
  Provides struct and type for a CorporationsCorporationIdContainersLogsGet
  """

  @type t :: %__MODULE__{
          action: String.t(),
          character_id: integer,
          container_id: integer,
          container_type_id: integer,
          location_flag: String.t(),
          location_id: integer,
          logged_at: DateTime.t(),
          new_config_bitmask: integer | nil,
          old_config_bitmask: integer | nil,
          password_type: String.t() | nil,
          quantity: integer | nil,
          type_id: integer | nil
        }

  defstruct [
    :action,
    :character_id,
    :container_id,
    :container_type_id,
    :location_flag,
    :location_id,
    :logged_at,
    :new_config_bitmask,
    :old_config_bitmask,
    :password_type,
    :quantity,
    :type_id
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      action:
        {:enum,
         [
           "add",
           "assemble",
           "configure",
           "enter_password",
           "lock",
           "move",
           "repackage",
           "set_name",
           "set_password",
           "unlock"
         ]},
      character_id: :integer,
      container_id: :integer,
      container_type_id: :integer,
      location_flag:
        {:enum,
         [
           "AssetSafety",
           "AutoFit",
           "Bonus",
           "Booster",
           "BoosterBay",
           "Capsule",
           "CapsuleerDeliveries",
           "Cargo",
           "CorpDeliveries",
           "CorpSAG1",
           "CorpSAG2",
           "CorpSAG3",
           "CorpSAG4",
           "CorpSAG5",
           "CorpSAG6",
           "CorpSAG7",
           "CorporationGoalDeliveries",
           "CrateLoot",
           "Deliveries",
           "DroneBay",
           "DustBattle",
           "DustDatabank",
           "FighterBay",
           "FighterTube0",
           "FighterTube1",
           "FighterTube2",
           "FighterTube3",
           "FighterTube4",
           "FleetHangar",
           "FrigateEscapeBay",
           "Hangar",
           "HangarAll",
           "HiSlot0",
           "HiSlot1",
           "HiSlot2",
           "HiSlot3",
           "HiSlot4",
           "HiSlot5",
           "HiSlot6",
           "HiSlot7",
           "HiddenModifiers",
           "Implant",
           "Impounded",
           "InfrastructureHangar",
           "JunkyardReprocessed",
           "JunkyardTrashed",
           "LoSlot0",
           "LoSlot1",
           "LoSlot2",
           "LoSlot3",
           "LoSlot4",
           "LoSlot5",
           "LoSlot6",
           "LoSlot7",
           "Locked",
           "MedSlot0",
           "MedSlot1",
           "MedSlot2",
           "MedSlot3",
           "MedSlot4",
           "MedSlot5",
           "MedSlot6",
           "MedSlot7",
           "MobileDepotHold",
           "MoonMaterialBay",
           "OfficeFolder",
           "Pilot",
           "PlanetSurface",
           "QuafeBay",
           "QuantumCoreRoom",
           "Reward",
           "RigSlot0",
           "RigSlot1",
           "RigSlot2",
           "RigSlot3",
           "RigSlot4",
           "RigSlot5",
           "RigSlot6",
           "RigSlot7",
           "SecondaryStorage",
           "ServiceSlot0",
           "ServiceSlot1",
           "ServiceSlot2",
           "ServiceSlot3",
           "ServiceSlot4",
           "ServiceSlot5",
           "ServiceSlot6",
           "ServiceSlot7",
           "ShipHangar",
           "ShipOffline",
           "Skill",
           "SkillInTraining",
           "SpecializedAmmoHold",
           "SpecializedAsteroidHold",
           "SpecializedCommandCenterHold",
           "SpecializedFuelBay",
           "SpecializedGasHold",
           "SpecializedIceHold",
           "SpecializedIndustrialShipHold",
           "SpecializedLargeShipHold",
           "SpecializedMaterialBay",
           "SpecializedMediumShipHold",
           "SpecializedMineralHold",
           "SpecializedOreHold",
           "SpecializedPlanetaryCommoditiesHold",
           "SpecializedSalvageHold",
           "SpecializedShipHold",
           "SpecializedSmallShipHold",
           "StructureActive",
           "StructureFuel",
           "StructureInactive",
           "StructureOffline",
           "SubSystemBay",
           "SubSystemSlot0",
           "SubSystemSlot1",
           "SubSystemSlot2",
           "SubSystemSlot3",
           "SubSystemSlot4",
           "SubSystemSlot5",
           "SubSystemSlot6",
           "SubSystemSlot7",
           "Unlocked",
           "Wallet",
           "Wardrobe"
         ]},
      location_id: :integer,
      logged_at: {:string, :date_time},
      new_config_bitmask: :integer,
      old_config_bitmask: :integer,
      password_type: {:enum, ["config", "general"]},
      quantity: :integer,
      type_id: :integer
    ]
  end
end
